### ISSUE TITLE
define Usecases

### ISSUE THREAD

**Issue by reouno** [reouno/stock-data-server#6]
# Background

# Tasks
- [ ] define Usecase Interfaces (type class in Haskell)
- [ ] define input and output data types
- [ ] implement Usecase Interactor

# reference
https://qiita.com/nrslib/items/a5f902c4defc83bd46b8#usecase
